[build]
target = "armv7-unknown-linux-gnueabihf"
# rustflags = [
#   "-Z", "print-link-args"
# ]

[target.armv7-unknown-linux-gnueabihf]
linker = "/home/ibiyemi/projects/experiments/xcompile/opt/cross/bin/armv7l-linux-gnueabihf-gcc"
runner = "./run.sh"

[env]
LIBRARY_PATH = "/usr/armv7l-unknown-linux-gnueabihf/lib"
PKG_CONFIG_LIBDIR = "/usr/armv7l-unknown-linux-gnueabihf/lib/pkgconfig"
PKG_CONFIG_PATH = "/home/ibiyemi/projects/experiments/xcompile/copied-from-pi/usr/lib/arm-linux-gnueabihf/pkgconfig"
PKG_CONFIG_SYSROOT_DIR = "/usr/armv7l-unknown-linux-gnueabihf"
